name: Release New Version

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type - major, minor or patch'
        required: false
        default: ''
      preReleaseFlavor:
        description: 'Pre-Release flavor - rc, beta, or anything'
        required: false
        default: ''

jobs:
  create-release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node: '16'

      - name: Setup Git
        run: |
          git config --global user.name "devx-sauce-bot"
          git config --global user.email "devx.bot@saucelabs.com"

      - name: generate (pre-)release draft
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          if [ -z "${{ github.event.inputs.releaseType }}" ] && [ -z "${{ github.event.inputs.preReleaseFlavor }}" ]; then
            echo "No release type provided."
            exit 1
          fi

          if [ -n "${{ github.event.inputs.preReleaseFlavor }}" ]; then
            PRE_RELEASE_ARGS="--preRelease=${{ github.event.inputs.preReleaseFlavor }} --github.preRelease"
          fi

          npm ci

          npx release-it ${{ github.event.inputs.releaseType }} ${PRE_RELEASE_ARGS}

          TAG_NAME=$(cat version.txt)

          echo ::set-output name=tag_name::${TAG_NAME}

          # RELEASE_ID=$(curl -s -H "Authorization: token ${{ github.token }}" \
          #   https://api.github.com/repos/${{ github.repository }}/releases | \
          #   jq ".[] | select(.tag_name == \"${TAG_NAME}\") | .id")

          # echo ::set-output name=release_id::${RELEASE_ID}

      - name: Post Release Capture
        id: post-release
        run: |
          RELEASE_ID=$(curl -s -H "Authorization: token ${{ github.token }}" \
            https://api.github.com/repos/${{ github.repository }}/releases | \
            jq ".[] | select(.tag_name == \"${{ steps.release.outputs.tag_name }}\") | .id")

          echo ::set-output name=release_id::${RELEASE_ID}

      - name: Outputs
        run: |
          echo "tag_name: ${{ steps.release.outputs.tag_name }}"
          echo "release_id: ${{ steps.post-release.outputs.release_id }}"

    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      release_id: ${{ steps.post-release.outputs.release_id }}

  release-windows-bundle:
    runs-on: windows-latest
    needs: [create-release-draft]
    steps:
      - name: Verify Dependencies
        run: |
          if ( $null -eq "${{ needs.create-release-draft.outputs.tag_name }}" ) {
            echo "Missing required tag name"
            exit 1          
          }

          if ( $null -eq "${{ needs.create-release-draft.outputs.release_id }}" ) {
            echo "Missing required release ID"
            exit 1
          }

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node: '16'

      - name: Update Release version
        run: |
          npm version --no-git-tag-version ${{ needs.create-release-draft.outputs.tag_name }}

      - run: npm ci

      - name: Create Bundle
        run: npm run bundle

      - name: List bundle contents
        run: ls -R bundle/

      - name: Archive bundle
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Compress-Archive bundle/ puppeteer-replay-runner-win.zip
          azPSVersion: '3.1.0'

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ needs.create-release-draft.outputs.release_id }}/assets?name=puppeteer-replay-runner-win.zip
          asset_path: ./puppeteer-replay-runner-win.zip
          asset_name: puppeteer-replay-runner-win.zip
          asset_content_type: application/zip

  release-macos-bundle:
    runs-on: macos-latest
    needs: [create-release-draft]
    steps:
      - name: Verify Dependencies
        run: |
          if [ -z "${{ needs.create-release-draft.outputs.tag_name }}" ]; then
              echo "Missing required tag name"
              exit 1
          fi

          if [ -z "${{ needs.create-release-draft.outputs.release_id }}" ]; then
              echo "Missing required release ID"
              exit 1
          fi

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node: '16'

      - name: Update Release version
        run: |
          npm version --no-git-tag-version ${{ needs.create-release-draft.outputs.tag_name }}

      - run: npm ci

      - name: Create Bundle
        run: npm run bundle

      - name: List bundle contents
        run: ls -R bundle/

      - name: Archive bundle
        run: zip --symlinks -r puppeteer-replay-runner-macos.zip bundle/

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ needs.create-release-draft.outputs.release_id }}/assets?name=puppeteer-replay-runner-macos.zip
          asset_path: ./puppeteer-replay-runner-macos.zip
          asset_name: puppeteer-replay-runner-macos.zip
          asset_content_type: application/zip

  publish-release:
    runs-on: ubuntu-latest
    needs: [create-release-draft, release-windows-bundle, release-macos-bundle]
    steps:
      - name: Verify Dependencies
        run: |
          if [ -z "${{ needs.create-release-draft.outputs.release_id }}" ]; then
              echo "Missing required release ID"
              exit 1
          fi

      - name: Publish release
        run: |
          curl -f -X PATCH -H "Authorization: token ${{ github.token }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/${{ needs.create-release-draft.outputs.release_id }} \
            -d '{"draft":"false"}'
